package models

type ResellerDetails struct {
	Supersite2URL                    string `json:"supersite2url"`
	TwofactorgoogleauthEnabled       string `json:"twofactorgoogleauth_enabled"`
	Partialsupersite2URL             string `json:"partialsupersite2url"`
	Singaporegstenabled              string `json:"singaporegstenabled"`
	Telno                            string `json:"telno"`
	Password                         string `json:"password"`
	Isresellerrestricted             string `json:"isresellerrestricted"`
	Brandingurl                      string `json:"brandingurl"`
	Billingemailaddr                 string `json:"billingemailaddr"`
	State                            string `json:"state"`
	Useremail                        string `json:"useremail"`
	Billingfromname                  string `json:"billingfromname"`
	Salestelnocc                     string `json:"salestelnocc"`
	Parentsellingcurrencysymbol      string `json:"parentsellingcurrencysymbol"`
	Salescontactid                   string `json:"salescontactid"`
	Emailaddr                        string `json:"emailaddr"`
	Resellerid                       string `json:"resellerid"`
	Abuseemailaddr                   string `json:"abuseemailaddr"`
	IsDominicanTaxConfiguredByParent bool   `json:"isDominicanTaxConfiguredByParent"`
	Resellerstatus                   string `json:"resellerstatus"`
	Salesemailaddr                   string `json:"salesemailaddr"`
	Zip                              string `json:"zip"`
	Partnersiteurl                   string `json:"partnersiteurl"`
	Minreceiptrequire                string `json:"minreceiptrequire"`
	Abusefromname                    string `json:"abusefromname"`
	SwitchPanelEnabled               string `json:"switch_panel_enabled"`
	Technicalsupportmailaddr         string `json:"technicalsupportmailaddr"`
	Username                         string `json:"username"`
	Pin                              string `json:"pin"`
	Russiavatenabled                 string `json:"russiavatenabled"`
	Abusesignature                   string `json:"abusesignature"`
	Minimumaddfundamount             string `json:"minimumaddfundamount"`
	Salestelno                       string `json:"salestelno"`
	Isoldreseller                    string `json:"isoldreseller"`
	DirectpaymentdetailsReseller     string `json:"directpaymentdetails_reseller"`
	Stateid                          string `json:"stateid"`
	Salessignature                   string `json:"salessignature"`
	Name                             string `json:"name"`
	Ischildinfoallowed               string `json:"ischildinfoallowed"`
	Partialstorefronturl             string `json:"partialstorefronturl"`
	TwofactorauthEnabled             string `json:"twofactorauth_enabled"`
	FutureProductSignup              string `json:"futureProductSignup"`
	Salesfromname                    string `json:"salesfromname"`
	Billingtelnocc                   string `json:"billingtelnocc"`
	Company                          string `json:"company"`
	SfLangPref                       string `json:"sf_langPref"`
	Telnocc                          string `json:"telnocc"`
	Australiagstenabled              string `json:"australiagstenabled"`
	Indianservicetaxenabled          string `json:"indianservicetaxenabled"`
	Brandname                        string `json:"brandname"`
	ShowdirectpaymentReseller        string `json:"showdirectpayment_reseller"`
	Creationdt                       string `json:"creationdt"`
	Billingtelno                     string `json:"billingtelno"`
	Address1                         string `json:"address1"`
	Newzealandgstenabled             string `json:"newzealandgstenabled"`
	Sellingcurrencysymbol            string `json:"sellingcurrencysymbol"`
	DirectpaymentdetailsCustomer     string `json:"directpaymentdetails_customer"`
	Chargevat                        string `json:"chargevat"`
	Usesystemconversionrate          string `json:"usesystemconversionrate"`
	Technicalsupporttelno            string `json:"technicalsupporttelno"`
	TwofactorsmsauthEnabled          string `json:"twofactorsmsauth_enabled"`
	Fundthreshold                    string `json:"fundthreshold"`
	Minimumbillingamount             string `json:"minimumbillingamount"`
	Parentid                         string `json:"parentid"`
	Salespersonshash                 struct {
	} `json:"salespersonshash"`
	Totalreceipts             string `json:"totalreceipts"`
	Suffixurl                 string `json:"suffixurl"`
	Accountingcurrencysymbol  string `json:"accountingcurrencysymbol"`
	ShowdirectPaymentCustomer string `json:"showdirectPayment_customer"`
	Supportsautorenew         string `json:"supportsautorenew"`
	Country                   string `json:"country"`
	Conversionrate            string `json:"conversionrate"`
	Langpref                  string `json:"langpref"`
	Indiangstenabled          string `json:"indiangstenabled"`
	City                      string `json:"city"`
	Technicalsupporttelnocc   string `json:"technicalsupporttelnocc"`
	Parentbrandingurl         string `json:"parentbrandingurl"`
	Iswebpro                  string `json:"iswebpro"`
	Sendriskreportmail        string `json:"sendriskreportmail"`
	Partialpartnersiteurl     string `json:"partialpartnersiteurl"`
}

type ResellerBalance struct {
	Sellingcurrencysymbol        string  `json:"sellingcurrencysymbol"`
	Sellingcurrencybalance       float64 `json:"sellingcurrencybalance"`
	Sellingcurrencylockedbalance float64 `json:"sellingcurrencylockedbalance"`
}
